#include <conio.h>
#include <iostream.h>

void main ()
{
	clrscr();
   cout << "it is my first c++ program\n";
   cout << "i am sure that will be familiar with this";
   cout << "----------------------------\n";



// 2.buatlah 3 huruf nama anda

	cout << "GGGGGGGGG    EEEEEEEEEEE   TTTTTTTTTTT\n";
   cout << "GGGGGGGGG    EEEEEEEEEEE   TTTTTTTTTTT\n";
   cout << "GG           EE                TTT    \n";
   cout << "GG  GGGGG    EEEEEEEEEEE       TTT    \n";
   cout << "GG  GGGGG    EEEEEEEEEEE       TTT    \n";
   cout << "GG     GG    EE                TTT    \n";
   cout << "GGGGGGGGG    EEEEEEEEEEE       TTT    \n";
   cout << "GGGGGGGGG    EEEEEEEEEEE       TTT    \n";
   getch();
}